sourceIfExists () {
    if [ -f "$1" ]; then
        source "$1"
    fi
}

export WORKSTATION_DIR="${WORKSTATION_DIR:-~/workstation}"

sourceIfExists ${WORKSTATION_DIR}/lib/shell/settings.sh
sourceIfExists ${WORKSTATION_DIR}/lib/shell/paths.sh
sourceIfExists ${WORKSTATION_DIR}/hosts/current/zshrc.sh

export EDITOR=emacsclient
export GIT_EDITOR=$EDITOR

export LANG=en_US.UTF-8

# TODO figure out how to make this work in zsh
# shopt -s extglob

export HISTCONTROL=erasedups
export HISTSIZE=10000
export HISTCONTROL=ignoreboth
export HISTFILESIZE=2000

do_command_done_alert() {
    osascript -e 'display dialog "Command Done!"'
}

alert_when_done() {
    if test -n "$1";
    then
        while kill -0 $1
        do
            sleep 1
        done
    fi
    do_command_done_alert
}

sourceIfExists /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
sourceIfExists ~/.nix-profile/etc/profile.d/hm-session-vars.sh
sourceIfExists ~/workstation/lib/shell/funcs.sh
sourceIfExists ~/.ghcup/env

sourceIfExists ${WORKSTATION_DIR}/lib/shell/funcs.sh
