name:                wshs
version:             0.1.0.0
github:              "githubuser/wshs"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/wshs#readme>

default-extensions:
- OverloadedStrings
- RecordWildCards
- DuplicateRecordFields
- LambdaCase
- AllowAmbiguousTypes
- GADTs
- QuasiQuotes

dependencies:
- base >= 4.7 && < 5
- turtle
- text
- string-interpolate
- directory
- bytestring
- aeson
- shelly
- optional-args
- raw-strings-qq
- trifecta
- parsers
- utf8-string

library:
  source-dirs: src

executables:
  bww:
    main:                app/Bww.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - wshs
  ws:
    main:                app/Ws.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - wshs

tests:
  wshs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wshs
    - hspec
