# Github Actions CI
# Importantly, github CI support macos environments.

# Daily build to ensure that potential problems get caught (NB: I have had issues
# where a working setup no longer worked due to bit rot, which would have been
# caught with a regular build like this).

# I am running up close to maximum execution time, so very likely I will need to
# refactor/come up with some other way to do this.

# [[file:../../workstation.org::*Github Actions CI][Github Actions CI:1]]
name: CI

on:
  push:
  schedule:
  - cron: '0 0 * * *'  # every day at midnight

jobs:
  build:
    strategy:
      matrix:
        os:
# https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
        - macos-13 # x86
        - macos-latest # aarch
        - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3

    - name: Run a one-line script
      env:
        BW_CLIENTID: ${{ secrets.BW_CLIENTID }}
        BW_CLIENTSECRET: ${{ secrets.BW_CLIENTSECRET }}
        WS_BW_MASTER_PASS: ${{ secrets.WS_BW_MASTER_PASS }}
      run: ./test/ci.sh
# Github Actions CI:1 ends here
